OrganizationalStructure/Models/ErrorViewModel.cs
namespace OrganizationalStructure.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

OrganizationalStructure/Controllers/ImportController.cs
using Microsoft.AspNetCore.Mvc;
using OrganizationalStructure.Models;
using System.Diagnostics;
using BL.Abstract;


namespace OrganizationalStructure.Controllers
{
    public class ImportController : Controller
    {
        private readonly IImportService _importService;

        public ImportController(IImportService importService)
        {
            _importService = importService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Import(IFormFile fileExcel)
        {
            if (ModelState.IsValid)
            {
                await _importService.ImportExcelFileAsync(fileExcel);
            }
            return RedirectToAction("Index");
        }
    }
}

OrganizationalStructure/Controllers/OrgStructureController.cs
using Microsoft.AspNetCore.Mvc;
using BL.Abstract;

namespace OrganizationalStructure.Controllers
{
    public class OrgStructureController : Controller
    {
        private readonly IOrgStructureService _orgStructureService;

        public OrgStructureController(IOrgStructureService orgStructureService)
        {
            _orgStructureService = orgStructureService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(string parrentDepartmentName)
        {
            var departments = await _orgStructureService.GetChildDepartmentsByParrentAsync(parrentDepartmentName);
            ViewBag.Parrent = parrentDepartmentName;
            return View(departments);
        }

        [HttpPost]
        public async Task<IActionResult> GetPositionsAndEmployeeCount(string departmentName)
        {
            var countCollection = await _orgStructureService.GetEmployeesAndPositionsCount(departmentName);
            return View(countCollection);
        }
    }
}

OrganizationalStructure/Views/Import/Index.cshtml
@{
    ViewData["Title"] = "Импорт Excel";
}
<h2>Импорт файла Excel</h2>
<div>
    @using (Html.BeginForm("Import", "Import", FormMethod.Post, new { enctype = "multipart/form-data", id = "frm-excel" }))
    {
        <div>
            Загрузите файл Excel:
            <input required type = "file" name = "fileExcel" id = "fileExcel /">
            <div>
                <input type = "submit" value = "Загрузить" />
            </div>
        </div>
    }
</div>

OrganizationalStructure/Views/OrgStructure/GetPositionsAndEmployeeCount.cshtml
@model IReadOnlyCollection<int>
@if (Model is null)
{
    <div>
        В отделе 0 позиций и 0 сотрудников
    </div>
}
else
{
    <div>
        В отделе на данный момент @Model.First() позиций и @Model.Last() сотрудников
    </div>
}

OrganizationalStructure/Views/OrgStructure/Index.cshtml
@model IReadOnlyCollection<string>

<h3>Получение организационной структуры</h3>
<div>
    @using (Html.BeginForm("Index", "OrgStructure", FormMethod.Post, new { enctype = "multipart/form-data", id = "parrentDepartmentName" }))
    {
        <div>
            Введите название родительского отдела:
            <input required type="text" name="parrentDepartmentName" id="parrentDepartmentName /">
            <div>
                <input type="submit" value="Подтвердить" />
            </div>
        </div>
    }
</div>
@if (Model is null)
{

}
else
{
    @if (Model.Count == 0)
    {
        <div>
            <br />
            Отсутствуют связанные отделы
        </div>
    }
    else
    {
        <br />
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Отдел
                    </th>
                    <th>
                        Родительский отдел
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var department in Model)
                {
                    <tr>
                        <td width="50%">@department</td>
                        <td width="50%">@ViewBag.Parrent</td>
                    </tr>
                }
            </tbody>
        </table>
    }
}
<br/>

<h3>Получение информации по количеству сотрудников и позиций в отделе</h3>
<div>
    @using (Html.BeginForm("GetPositionsAndEmployeeCount", "OrgStructure", FormMethod.Post, new { enctype = "multipart/form-data", id = "DepartmentName" }))
    {
        <div>
            Введите название отдела:
            <input required type="text" name="DepartmentName" id="DepartmentName /">
            <div>
                <input type="submit" value="Подтвердить" />
            </div>
        </div>
    }
</div>

OrganizationalStructure/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OrganizationalStructure</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OrganizationalStructure.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Import" asp-action="Index">OrganizationalStructure</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Import" asp-action="Index">Импорт</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OrgStructure" asp-action="Index">Организационная структура</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>